### ISSUE TITLE
Allow port-access in the pipeline

### ISSUE THREAD

**Issue by Fixstars-momoko** [fixstars/ion-kit#161]
Currently, the output in the form of Halide::Func[] allows access to each buffer after port mapping from the output port of a pipeline.

TODO:

- Add the feature to access each buffer by index so that each buffer can be used as an input for the following BB.
- Update the Python bindings along with the above change.

**Comment by xinyuli1204** [comment]
Python Status:[167](https://github.com/fixstars/ion-kit/pull/167)

**Comment by Fixstars-momoko** [comment]
https://github.com/fixstars/ion-kit/pull/164
https://github.com/fixstars/ion-kit/pull/167
https://github.com/fixstars/ion-kit/pull/172
