### ISSUE TITLE
Publish Python binding

### ISSUE THREAD

**Issue by Fixstars-iizuka** [fixstars/ion-kit#195]
- ~~Better syntax for Builder/Node/Port~~ (Backlog)
- ~~Design reference counting for c_ion objects~~  (Backlog)
- Publish on PyPI
  - Package Naming 
  - Versioning
  - Allows users to install by `pip install <name of the module>`

**Comment by xinyuli1204** [comment]
https://pypi.org/project/ion-kit-python/

**Comment by xinyuli1204** [comment]
`pip install <name of the module>`
May I ask is it means `pip install ionpy`?
since **pip** search the package index to install. And ionpy as a package name has already been taken. Also ion-python has the exact same name with https://github.com/amazon-ion/ion-python

**Comment by iitaku** [comment]
How about pip install ion-kit?

**Comment by iitaku** [comment]
Probably we can use `ion` as module name and `ion-kit` as package name.

**Comment by iitaku** [comment]
Is it possible to include a prebuilt ion-kit binary package in the package which is installed through pip?

**Comment by xinyuli1204** [comment]
> ion

you mean include libxxx.so, for example? I will check

**Comment by xinyuli1204** [comment]
## Naming Convention
1. Package: ion-python  Module: ionpy
2. Package: ion-kit Module: ion
3. Package: ion-python  Module: ion
2. include module
<img width="726" alt="Screenshot 2024-01-18 at 10 09 07 AM" src="https://github.com/fixstars/ion-kit/assets/143661893/1da9a3f0-c6a4-47a7-8529-bd793039c836">

```

[tool.setuptools.package-data]
ionpy = ["module/macos/*", "module/linux/*", "module/windows/*"]

```

**Comment by xinyuli1204** [comment]
1. reduce size
2. include ion-bb

**Comment by xinyuli1204** [comment]
https://github.com/fixstars/ion-kit/pull/211

**Comment by xinyuli1204** [comment]
> 2. include ion-bb  

ion_bb = ctypes.cdll.LoadLibrary(ion_bb_module)

**Comment by xinyuli1204** [comment]
If Include all the prebuilt binary
```
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         File too large. Limit for project 'ionpy' is 100 MB. See               
         https://test.pypi.org/help/#file-size-limit for more information.     
```

**Comment by iitaku** [comment]
@xinyuli1204 Can we create platform-specific wheels? https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/

**Comment by xinyuli1204** [comment]
FYI, A simple line in CmakeFile seems to be fine. Tested both on linux and mac
I will push the code later and also test on TestPYPI first.

```
if(APPLE)
    set(CMAKE_INSTALL_RPATH "@loader_path")
elseif(UNIX)
    set(CMAKE_INSTALL_RPATH "$ORIGIN")
endif()
```

### check binary 
```
$ readelf -d libion-core.so
Dynamic section at offset 0x106688 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libHalide.so.16]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libion-core.so]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
```
```
(base) xinyuli@xinyus-air lib %  otool -l  libion-core.dylib  | grep RPATH -A2

          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
```
```
(venv) (base) xinyuli@xinyus-air dist % python -c "import ionpy"  
(venv) (base) xinyuli@xinyus-air dist % 
```
```
(base) xinyu.li@spica:~/ion-kit/python/dist$ python -c "import ionpy"  
(base) xinyu.li@spica:~/ion-kit/python/dist$ 
```

**Comment by xinyuli1204** [comment]
mv [Publish Python binding](https://github.com/fixstars/ion-kit/issues/195) to  [CICD for Python module release ](https://github.com/fixstars/ion-kit/issues/229)

**Comment by Fixstars-iizuka** [comment]
#236
