### ISSUE TITLE
Case-sensitivity for ionpy Param

### ISSUE THREAD

**Issue by Fixstars-momoko** [fixstars/ion-kit#216]
The line below does not allow users to pass GenICam feature keys which are case-sensitive such as `Gain` and `ExposureTime`

https://github.com/fixstars/ion-kit/blob/5b5f9545b3788490a1776389d5cdc490d0dd510a/python/ionpy/Param.py#L21

**Comment by xinyuli1204** [comment]
https://github.com/fixstars/ion-kit/pull/218
```
    p1 = Param(key='iamkey1', val="IAMKEY")  # 'IAMKEY'
    p2 = Param(key='iamkey2', val="iamkey")  # 'iamkey'
    p3 = Param(key='iamkey3', val=1)  # '1'
    p4 = Param(key='iamkey4', val=0.1)  # '0.1'
    p5 = Param(key='iamkey5', val=True)   # 'true'
    p6 = Param(key='iamkey6', val=False)  # 'false'
```
