### ISSUE TITLE
with_bb_module not work

### ISSUE THREAD

**Issue by Fixstars-momoko** [fixstars/ion-kit#223]
with ionpy 1.2.0, the line to load dynamic module caused the error. The program works without the following line.

```
builder.with_bb_module('ion-bb') 
```

**Comment by xinyuli1204** [comment]
I don't know if this is the reason, but inside ionpy, it has prebuilt dll which based on ion-kit 1.2, but in sensing dev it seems to have 1.0., which is not compatible.
Maybe we can change native.py , and make it rely on sensing-dev tentatively.
if platform.system()  == 'Windows':
    ion_core_module = find_library('ion-core.dll')
ion_core_module = find_library('ion-bb.dll')

**Comment by xinyuli1204** [comment]
only on windows
