### ISSUE TITLE
Upgrade ion-kit to be compatible with halide17

### ISSUE THREAD

**Issue by xinyuli1204** [fixstars/ion-kit#261]
## Context or motivation
Halide has release the latest v17.0.1 
## Goal 
we want ion-kit to be compatible with the latest halide
Two major change is:
1. ParamMap has been removed entirely from the public API. (we should remove our portmap as well)
2. Halide::Parameter has been moved to the public Halide API (it was formerly "internal" and not intended for public use).
## TODO

- [x] update github cdci
- [x] remove portmap
- [x] make Halide::internal::Parameter as public api

**Comment by xinyuli1204** [comment]
@iitaku is this a good timing to remove the portmap?

**Comment by iitaku** [comment]
Resolved in #260
