### ISSUE TITLE
Support implicit I/O mapping feature

### ISSUE THREAD

**Issue by iitaku** [fixstars/ion-kit#283]
Some framework built on the ion-kit requires dynamic parameters. The dynamic parameters are preferred to be implemented as `BuildingBlock::Input` or `BuildingBlock::Output`. But, currently, `Input` should be bound with `ion::Buffer` or another port. `Output` can be unbound, but it is not evaluated if `Output` is unbound. This enforces framework/application to connect all dynamic parameters explicitly. Our motivation is to support dynamic parameters without connecting these ports with others on the Framework layer by providing API to determine unbound I/O port.

We will implement:

- API to iterate unbound I/O on `ion::Builder` and `ion::Graph`

Framework can iterate unbound I/O and they can bind it with arbitrary address.

**Comment by xinyuli1204** [comment]
https://github.com/fixstars/ion-kit/pull/284
