### ISSUE TITLE
ion-python packaging workflow does not support non-latest

### ISSUE THREAD

**Issue by Fixstars-momoko** [fixstars/ion-kit#295]
For the release of 1.8.3, https://github.com/fixstars/ion-kit/actions/runs/9768419414/job/27169386707 release downloader obtains the latest (v3.0.0) and this Halide version is 17 instead of 16 which release/v1 series requires.

**Comment by xinyuli1204** [comment]
done https://github.com/fixstars/ion-kit/actions/runs/9844206322

**Comment by Fixstars-momoko** [comment]
Solved on https://github.com/fixstars/ion-kit/pull/297
